name: 'SuperSub API'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: 'ubuntu-latest'
    services:
      redis:
        image: 'redis:alpine'
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: 'postgres:alpine'
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_DB: 'test'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v4'

      - name: 'Install Node.js'
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: 'Install the dependencies'
        run: 'npm install'

      - name: 'Lint the code'
        run: 'npm run lint'

      - name: 'Run Prisma migrations'
        env:
          DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/test'
        run: npx prisma migrate deploy

      - name: 'Test the codebase'
        env:
          REDIS_URL: 'redis://localhost:6379'
          SECRET_KEY: 'deeznut!in!your!face'
          LOG_LEVEL: 'info'
          DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/test'
        run: 'npm test --coverage'
